version: "3"

services:
  api:
    build: api/
    command: uvicorn main:app --reload --port 80 --host "0.0.0.0"
    ports:
      - 80:80
  bot:
    build: bot/
    command: python ./main.py

    network_mode: host

    depends_on:
      - api
